seederCfg:
  rootDirectory: /data/bt/seeder
  origin: x.x.x.x
  trackers: http://x.x.x.x:6969/announce
  limitSize: 1T
  downloadTimeout: 30
  storageBackend: fs
  port: 61008
daemonCfg:
  port: 55008
  verbose: true