clientCfg:
  rootDirectory: /data/bt/proxy
  trackers: http://x.x.x.x:6969/announce
  seeders: x.x.x.x:75008
  limitSize: 100G
  downloadRateLimit: 50M
  uploadRateLimit: 50M
  downloadTimeout: 30
  port: 61007
proxyCfg:
  port: 43002
  verbose: true
  rules: x.x.x.x
  certFile:
  keyFile: